platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
	pod 'PhoneVerificationController', :path => '../'
	pod 'SwiftGen'
end
